version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./app:/app
    links:
      - php
    command: [nginx-debug, "-g", "daemon off;"]
    restart: always

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    restart: always
